#!/usr/bin/env python3
"""
prep_training_data.py
─────────────────────
Converts each scan in data/scans/ from a raw PLY into a 512×512 density.png
that RoomFormer can train on. Run this before training.

  data/scans/
    scan_001/
      cloud.ply        ← input (from COLMAP dense or PLY drop)
      floor_plan.json  ← your annotation (saved from the browser)
      density.png      ← generated by this script
"""

import os, sys, glob, argparse
import numpy as np
from plyfile import PlyData
from PIL import Image
from scipy.spatial import KDTree

IMG_SIZE = 512


def load_ply(path):
    plydata = PlyData.read(path)
    v     = plydata['vertex']
    names = v.data.dtype.names
    xyz   = np.stack([v['x'], v['y'], v['z']], axis=1).astype(np.float32)

    if 'red' in names:
        rgb = np.stack([v['red'], v['green'], v['blue']], axis=1).astype(np.float32) / 255.
    elif 'f_dc_0' in names:
        C0  = 0.28209479177387814
        rgb = np.clip(0.5 + C0 * np.stack([v['f_dc_0'], v['f_dc_1'], v['f_dc_2']], axis=1), 0, 1).astype(np.float32)
    else:
        rgb = np.ones((len(xyz), 3), np.float32)

    return xyz, rgb


def clean_pcd(xyz, rgb):
    tree     = KDTree(xyz)
    dists, _ = tree.query(xyz, k=21)
    mean_d   = dists[:, 1:].mean(axis=1)
    mask     = mean_d < mean_d.mean() + 2.0 * mean_d.std()
    xyz, rgb = xyz[mask], rgb[mask]

    voxel     = 0.02
    ids       = np.floor(xyz / voxel).astype(np.int32)
    _, idx    = np.unique(ids, axis=0, return_index=True)
    return xyz[idx], rgb[idx]


def orient_z_up(xyz, rgb):
    ranges = xyz.max(0) - xyz.min(0)
    v      = int(np.argmin(ranges))
    if v == 2:
        return xyz, rgb
    R = {1: np.array([[1,0,0],[0,0,-1],[0,1,0]], np.float32),
         0: np.array([[0,1,0],[0,0,1],[1,0,0]], np.float32)}[v]
    return xyz @ R.T, rgb


def make_density_png(xyz, out_path):
    xy   = xyz[:, :2]
    mn   = xy.min(0)
    span = xy.max(0) - mn

    img = np.zeros((IMG_SIZE, IMG_SIZE), np.float32)
    ix  = np.clip(((xy[:, 0] - mn[0]) / (span[0] + 1e-6) * (IMG_SIZE - 1)).astype(int), 0, IMG_SIZE - 1)
    iy  = np.clip(((xy[:, 1] - mn[1]) / (span[1] + 1e-6) * (IMG_SIZE - 1)).astype(int), 0, IMG_SIZE - 1)
    np.add.at(img, (iy, ix), 1)
    img = np.minimum(img / (img.max() + 1e-8), 1.0)

    # Apply light Gaussian blur so RoomFormer sees solid walls, not just dots
    from scipy.ndimage import gaussian_filter
    img = gaussian_filter(img, sigma=2.0)
    img = np.clip(img / (img.max() + 1e-8), 0, 1)

    # Save as 3-channel PNG (RoomFormer expects RGB)
    arr = (img * 255).astype(np.uint8)
    rgb = np.stack([arr, arr, arr], axis=2)
    Image.fromarray(rgb).save(out_path)
    return mn, span


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--data', required=True, help='Path to data/scans/ dir')
    args = p.parse_args()

    scans = sorted(glob.glob(os.path.join(args.data, '*/')))
    if not scans:
        sys.exit(f'No scan folders found in {args.data}')

    ok = 0
    for scan_dir in scans:
        name    = os.path.basename(scan_dir.rstrip('/'))
        ply     = os.path.join(scan_dir, 'cloud.ply')
        gt_file = os.path.join(scan_dir, 'floor_plan.json')
        out_png = os.path.join(scan_dir, 'density.png')

        if not os.path.exists(ply):
            print(f'  skip {name} — no cloud.ply')
            continue
        if not os.path.exists(gt_file):
            print(f'  skip {name} — no floor_plan.json (annotate it first)')
            continue

        print(f'  prep {name}…', end=' ')
        try:
            xyz, rgb = load_ply(ply)
            xyz, rgb = clean_pcd(xyz, rgb)
            xyz, rgb = orient_z_up(xyz, rgb)
            make_density_png(xyz, out_png)
            print(f'{len(xyz):,} pts → {out_png}')
            ok += 1
        except Exception as e:
            print(f'ERROR: {e}')

    print(f'\n[prep] {ok}/{len(scans)} scans ready for training.')
    if ok == 0:
        print('[prep] Add cloud.ply + floor_plan.json to each scan folder.')


if __name__ == '__main__':
    main()
