#!/usr/bin/env python3
"""
train_roomformer.py — Fine-tune RoomFormer on real scan data.
Runs ON the RunPod GPU pod. Streams progress to stdout (visible in fp.py).

Data format expected in --data dir:
  data/
    scan_001/
      density.png      (512×512 top-down density image, auto-generated by prep)
      floor_plan.json  (ground truth room polygons, exported from the browser)
    scan_002/
      ...
"""

import os, sys, json, glob, argparse, math
import numpy as np
from PIL import Image

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim

sys.path.insert(0, '/workspace/RoomFormer')

IMG_SIZE    = 512
DEVICE      = 'cuda' if torch.cuda.is_available() else 'cpu'


# ── Dataset ───────────────────────────────────────────────────────────────────

class FloorPlanDataset(Dataset):
    def __init__(self, data_dir, max_polys=20, max_corners=40):
        self.max_polys   = max_polys
        self.max_corners = max_corners
        self.samples     = []

        for scan_dir in sorted(glob.glob(os.path.join(data_dir, '*/'))):
            density = os.path.join(scan_dir, 'density.png')
            gt_file = os.path.join(scan_dir, 'floor_plan.json')
            if os.path.exists(density) and os.path.exists(gt_file):
                self.samples.append((density, gt_file))

        if not self.samples:
            sys.exit(f'[train] No samples found in {data_dir}\n'
                     f'        Run: python fp.py prep   to generate density.png files')
        print(f'[train] {len(self.samples)} samples loaded')

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        density_path, gt_path = self.samples[idx]

        # Load density image → [3, H, W] float tensor
        img = np.array(Image.open(density_path).convert('RGB'), dtype=np.float32) / 255.
        img = torch.from_numpy(img).permute(2, 0, 1)  # [3,H,W]

        # Load ground truth polygons
        with open(gt_path) as f:
            gt = json.load(f)

        # Convert polygons to padded tensor [max_polys, max_corners, 2]
        # Coordinates normalised to [0,1] relative to image size
        polys  = torch.zeros(self.max_polys, self.max_corners, 2)
        labels = torch.zeros(self.max_polys, dtype=torch.long)   # 1 = room exists

        rooms = gt.get('rooms', [])
        for pi, room in enumerate(rooms[:self.max_polys]):
            poly = room.get('poly', [])
            for ci, (x, y) in enumerate(poly[:self.max_corners]):
                polys[pi, ci, 0] = x / (gt.get('width',  IMG_SIZE) or IMG_SIZE)
                polys[pi, ci, 1] = y / (gt.get('height', IMG_SIZE) or IMG_SIZE)
            labels[pi] = 1

        return img, polys, labels


# ── Loss ──────────────────────────────────────────────────────────────────────

def compute_loss(outputs, target_polys, target_labels):
    """
    Simplified matching loss:
    - Room existence: BCE on pred_logits vs target_labels
    - Polygon coords: L1 on pred_coords vs target_polys (for matched rooms)
    """
    pred_logits = outputs['pred_logits']  # [B, num_polys, 2]
    pred_coords = outputs['pred_coords']  # [B, num_polys, max_corners, 2]

    B = pred_logits.shape[0]

    # Room existence loss
    exist_loss = F.cross_entropy(
        pred_logits.reshape(-1, 2),
        target_labels.reshape(-1),
    )

    # Coordinate regression loss (only for rooms that exist)
    mask = target_labels.bool()   # [B, num_polys]
    if mask.any():
        coord_loss = F.l1_loss(
            pred_coords[mask],
            target_polys[mask],
        )
    else:
        coord_loss = torch.tensor(0., device=pred_logits.device)

    return exist_loss + 5.0 * coord_loss, exist_loss.item(), coord_loss.item()


# ── Training loop ─────────────────────────────────────────────────────────────

def train(args):
    from models import build_model
    from util.misc import NestedTensor

    # Build model with same config as pretrained checkpoint
    class Args:
        backbone            = 'resnet50'
        position_embedding  = 'sine'
        hidden_dim          = 256
        dropout             = 0.1
        nheads              = 8
        dim_feedforward     = 1024
        enc_layers          = 6
        dec_layers          = 6
        pre_norm            = False
        num_queries         = 800
        num_polys           = 20
        num_feature_levels  = 4
        dec_n_points        = 4
        enc_n_points        = 4
        masks               = False
        lr_backbone         = 1e-5

    model, criterion, _ = build_model(Args())

    # Load pretrained checkpoint
    ckpt_path = args.pretrained or '/models/roomformer/checkpoints/roomformer_scenecad.pth'
    if not os.path.exists(ckpt_path):
        ckpt_path = '/models/roomformer/checkpoints/roomformer_stru3d.pth'
    print(f'[train] Loading pretrained weights: {ckpt_path}')
    ckpt = torch.load(ckpt_path, map_location='cpu')
    model.load_state_dict(ckpt['model'], strict=False)
    model = model.to(DEVICE)

    dataset = FloorPlanDataset(args.data)
    n_val   = max(1, len(dataset) // 5)
    n_train = len(dataset) - n_val
    train_ds, val_ds = torch.utils.data.random_split(dataset, [n_train, n_val])

    train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True,  num_workers=2)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch, shuffle=False, num_workers=2)

    # Fine-tune with a low LR — backbone is frozen, only transformer heads learn
    for p in model.backbone.parameters():
        p.requires_grad = False
    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=args.lr, weight_decay=1e-4,
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    os.makedirs(args.output, exist_ok=True)
    best_val_loss = float('inf')

    print(f'[train] Starting: {args.epochs} epochs  lr={args.lr}  '
          f'train={n_train}  val={n_val}  device={DEVICE}')
    print('[train] ' + '─' * 60)

    for epoch in range(1, args.epochs + 1):
        # ── Train
        model.train()
        t_loss = 0
        for imgs, polys, labels in train_loader:
            imgs   = imgs.to(DEVICE)
            polys  = polys.to(DEVICE)
            labels = labels.to(DEVICE)

            B, C, H, W = imgs.shape
            mask    = torch.zeros(B, H, W, dtype=torch.bool, device=DEVICE)
            samples = NestedTensor(imgs, mask)

            outputs = model(samples)
            loss, exist_l, coord_l = compute_loss(outputs, polys, labels)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
            optimizer.step()
            t_loss += loss.item()

        scheduler.step()

        # ── Validate
        model.eval()
        v_loss = 0
        with torch.no_grad():
            for imgs, polys, labels in val_loader:
                imgs, polys, labels = imgs.to(DEVICE), polys.to(DEVICE), labels.to(DEVICE)
                B, C, H, W = imgs.shape
                mask    = torch.zeros(B, H, W, dtype=torch.bool, device=DEVICE)
                samples = NestedTensor(imgs, mask)
                outputs = model(samples)
                loss, _, _ = compute_loss(outputs, polys, labels)
                v_loss += loss.item()

        t_avg = t_loss / len(train_loader)
        v_avg = v_loss / len(val_loader)
        star  = ' ← best' if v_avg < best_val_loss else ''
        print(f'[train] epoch {epoch:3d}/{args.epochs}  '
              f'train={t_avg:.4f}  val={v_avg:.4f}{star}')

        if v_avg < best_val_loss:
            best_val_loss = v_avg
            torch.save({'model': model.state_dict(), 'epoch': epoch, 'val_loss': v_avg},
                       os.path.join(args.output, 'best.pth'))

    print(f'[train] Done. Best val loss: {best_val_loss:.4f}')
    print(f'[train] Checkpoint: {args.output}/best.pth')


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--data',       required=True, help='Path to training data dir')
    p.add_argument('--output',     default='/workspace/checkpoints')
    p.add_argument('--pretrained', default=None,  help='Override pretrained ckpt path')
    p.add_argument('--epochs',     type=int,   default=50)
    p.add_argument('--lr',         type=float, default=1e-5)
    p.add_argument('--batch',      type=int,   default=4)
    train(p.parse_args())
